package lt.vu.mybatis.model;

public class Player {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.ID
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    private byte[] id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.AGE
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.HEIGHT
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.NAME
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.TEAM_ID
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    private byte[] teamId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.ID
     *
     * @return the value of PUBLIC.PLAYER.ID
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public byte[] getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.ID
     *
     * @param id the value for PUBLIC.PLAYER.ID
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public void setId(byte[] id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.AGE
     *
     * @return the value of PUBLIC.PLAYER.AGE
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.AGE
     *
     * @param age the value for PUBLIC.PLAYER.AGE
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.HEIGHT
     *
     * @return the value of PUBLIC.PLAYER.HEIGHT
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.HEIGHT
     *
     * @param height the value for PUBLIC.PLAYER.HEIGHT
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.NAME
     *
     * @return the value of PUBLIC.PLAYER.NAME
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.NAME
     *
     * @param name the value for PUBLIC.PLAYER.NAME
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.TEAM_ID
     *
     * @return the value of PUBLIC.PLAYER.TEAM_ID
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public byte[] getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.TEAM_ID
     *
     * @param teamId the value for PUBLIC.PLAYER.TEAM_ID
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public void setTeamId(byte[] teamId) {
        this.teamId = teamId;
    }
}