package lt.vu.mybatis.model;

public class Team {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.ID
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    private byte[] id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.BUDGET
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    private Integer budget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.COUNTRY
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.NAME
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.ID
     *
     * @return the value of PUBLIC.TEAM.ID
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public byte[] getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.ID
     *
     * @param id the value for PUBLIC.TEAM.ID
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public void setId(byte[] id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.BUDGET
     *
     * @return the value of PUBLIC.TEAM.BUDGET
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public Integer getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.BUDGET
     *
     * @param budget the value for PUBLIC.TEAM.BUDGET
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public void setBudget(Integer budget) {
        this.budget = budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.COUNTRY
     *
     * @return the value of PUBLIC.TEAM.COUNTRY
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.COUNTRY
     *
     * @param country the value for PUBLIC.TEAM.COUNTRY
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.NAME
     *
     * @return the value of PUBLIC.TEAM.NAME
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.NAME
     *
     * @param name the value for PUBLIC.TEAM.NAME
     *
     * @mbg.generated Mon Apr 20 22:50:03 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}